### ISSUE TITLE
Incorrect @brief in osRecursiveMutexWait()

### ISSUE THREAD

**Issue by jubeormk1** [xpacks/freertos#1]
https://github.com/xpacks/freertos/blob/47408ce37e11bd643e84b491daac84cb313a1d57/cmsis/src/cmsis_os_freertos.c#L1675

Probably this is not the place responsible of this code, but it should be wait for a recursive mutex. Not really important but the comment is incorrect. We all may copy paste.

**Comment by ilg-ul** [comment]
Thank you for the report.

I fixed the comment in commit https://github.com/xpacks/freertos/commit/785821bf4e6039629235370d4c7544b65349f326.

**Comment by jubeormk1** [comment]
Great, I was browsing.

Good job!
